insert into categories (title) VALUES ('Arts & Humanities');
insert into categories (title) VALUES ('Cars & Transportation');
insert into categories (title) VALUES ('Dining Out');
insert into categories (title) VALUES ('Environment');
insert into categories (title) VALUES ('Games & Recreation');
insert into categories (title) VALUES ('Local Businesses');
insert into categories (title) VALUES ('Politics & Government');
insert into categories (title) VALUES ('Social Science');
insert into categories (title) VALUES ('Travel');
insert into categories (title) VALUES ('Beauty & Style');
insert into categories (title) VALUES ('Computers & Internet');
insert into categories (title) VALUES ('Education & Reference');
insert into categories (title) VALUES ('Family & Relationships');
insert into categories (title) VALUES ('Health');
insert into categories (title) VALUES ('News & Events');
insert into categories (title) VALUES ('Pregnancy & Parenting');
insert into categories (title) VALUES ('Society & Culture');
insert into categories (title) VALUES ('Business & Finance');
insert into categories (title) VALUES ('Consumer Electronics');
insert into categories (title) VALUES ('Entertainment & Music');
insert into categories (title) VALUES ('Food & Drink');
insert into categories (title) VALUES ('Home & Garden');
insert into categories (title) VALUES ('Pets');
insert into categories (title) VALUES ('Science & Mathematics');
insert into categories (title) VALUES ('Sports');
insert into categories (title) VALUES ('Misc');