CREATE TABLE BLOGS(
	BLOGID SERIAL PRIMARY KEY,
	TITLE VARCHAR(100) NOT NULL,
	CREATION DATE,
	USERID INT CONSTRAINT fk_userid REFERENCES Users      (userid) ON DELETE CASCADE,
	CATID  INT CONSTRAINT fk_catid  REFERENCES Categories (catid)  ON DELETE CASCADE
);