CREATE TABLE COMMENTS(
	COMMENTID SERIAL PRIMARY KEY,
	BODY VARCHAR(500) NOT NULL,
	PUBDATE TIMESTAMP NOT NULL,
	USERID 		INT CONSTRAINT fk_userid REFERENCES Users 	(userid) 	ON DELETE CASCADE,
	POSTID 		INT CONSTRAINT fk_postid REFERENCES Posts 	(postid) 	ON DELETE CASCADE,
	REPLYTOID	INT CONSTRAINT fk_commid REFERENCES Comments(commentid) ON DELETE CASCADE
);