CREATE TABLE POSTS(
	POSTID SERIAL PRIMARY KEY,
	TITLE VARCHAR(100) NOT NULL,
	SMALLTITLE VARCHAR(100),
	POST VARCHAR(10000) NOT NULL,
	SMALLPOST VARCHAR(200),
	PUBDATE TIMESTAMP NOT NULL,
	VIEWS INT,
	BLOGID INT CONSTRAINT fk_blogid REFERENCES Blogs (blogid) ON DELETE CASCADE
);