CREATE TABLE USERS(
    USERID SERIAL PRIMARY KEY,
    USERNAME VARCHAR(100) UNIQUE,
    PASSWORD VARCHAR(500) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE,
    AVATAR VARCHAR(500),
    NAME VARCHAR(100) NOT NULL,
    SURNAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(3000),
    ENABLED BOOLEAN NOT NULL,
    ADMIN BOOLEAN NOT NULL,
    CREATION DATE
);

CREATE UNIQUE INDEX username_lower_case on Users (lower(username));
CREATE UNIQUE INDEX email_lower_case 	on Users (lower(email));